# SCLER - SC Localization Enhancer Russian
# user_dict.ini - пользовательский словарь замен
# Добавьте строки в формате:
#   ключ = значение
# Программа заменит значение ключа в global.ini на указанное.
# Файл должен быть в кодировке ANSI (Windows-1251).
#
# ВНИМАНИЕ: Необдуманная замена строк может привести
# к неработоспособности игры. Делайте замены осторожно.
# При нарушении работоспособности игры восстановите оригинальный
# файл global.ini из резервной копии (global.ini.noblueprints.bak).
#
# Для включения функции установите USE_USER_DICT=1 в SCLER.cfg.
#
# Примеры замены:
# Исходный текст в игре: ЛИФТ ВЫЗВАН
#ui_interactor_elevator_called=УЖЕ ЕДЕТ
# Добавление номера позволяет выделить технику в списках, например в ASOP
#vehicle_NameRSI_Perseus=1.RSI Perseus