# SCLER - SC Localization Enhancer Russian
# user_notes.ini - пользовательские заметки к миссиям Star Citizen
# Файл должен быть в кодировке ANSI (Windows-1251)
# Добавьте строки в формате:
#   ключ_миссии = ваш текст
# Текст будет добавлен в конец описания миссии.
# Ограничение: до 256 символов.
# Пример:
# _______линейка_______=        10        20        30        40        50        60        70        80        90       100       110       120       130       140       150       160       170       180       190       200       210       220       230       240       250
TheCollector_Intro_Desc=Рога тундровых копионов могут быть найдены в тундре, например около Shubin Mining Facility SM0-13 или MT DataCenter KH3-AAE-L. Может быть изменено в новых версиях игры - проверь условия квеста.
